### ISSUE TITLE
Company

### ISSUE THREAD

**Issue by despiegk** [Incubaid/crm#1]
- add message (action), needs to be very easy to start new message
- easier way to add/remove telephones & emails (now go to separate list...): 

![image](https://user-images.githubusercontent.com/6021844/30000575-e7aeaa74-9071-11e7-8e6f-0285545077e1.png)

just ability to add tel nr

- there can be more than 1 email (same behaviour as tel nr)
- adding task on edit should be much easier
- order of fields not ok: name, description, ... 

created & updated at should not been seen in edit

![image](https://user-images.githubusercontent.com/6021844/30000582-2dad45c6-9072-11e7-9037-d350bb6ecb29.png)
in stead of showing edit/view can we just make it a link & go only to view?

**Comment by xmonader** [comment]
![screenshot_2017-09-03_15-21-42](https://user-images.githubusercontent.com/64129/30003311-ff56378a-90c3-11e7-8a49-ae3239cc1f7e.png)

Fields ordered
Allowed multiple emails
referenced object will be rendered as link instead of (View/Edit) hyperlinks 
It'll look as the attached image
