### ISSUE TITLE
cannot click on tasks for user

### ISSUE THREAD

**Issue by despiegk** [Incubaid/crm#111]
![image](https://user-images.githubusercontent.com/6021844/31595855-188b16c2-b247-11e7-8d92-e034b7162ae4.png)

cannot click on tasks for user

**Comment by despiegk** [comment]
cannot filter on assignee in tasks list
![image](https://user-images.githubusercontent.com/6021844/31595867-34924e4e-b247-11e7-80ae-ea1e3c0ec80a.png)

**Comment by xmonader** [comment]
EDIT: still needs fixing

**Comment by xmonader** [comment]
Fixed
