### ISSUE TITLE
special view for tasks

### ISSUE THREAD

**Issue by despiegk** [Incubaid/crm#13]
make it easy for users to see their tasks

with optional filters (easy to select)
- sprint

sort
- urgency
- deadline

**Comment by xmonader** [comment]
![screenshot_2017-09-03_15-11-59](https://user-images.githubusercontent.com/64129/30003225-cf011c4a-90c2-11e7-99dc-30a242ad86ea.png)
![screenshot_2017-09-03_15-05-42](https://user-images.githubusercontent.com/64129/30003226-cf0d2706-90c2-11e7-878b-63283ffc66cc.png)

Filters are very easy to add for example the filter on sprints by name, 
also I allowed so sortable option on eta and priority
https://github.com/Incubaid/crm/commit/0424a9c3e245b8f93feed7ddd3d71239b8feb8f5
