### ISSUE TITLE
Control Dashboard to watch fundraising progress

### ISSUE THREAD

**Issue by nbabenko** [Incubaid/crm#141]
Create a configurable dashboard.
Dashboard should show 

- progress bar of amount raised vs target amount
- amount of unclosed leads
- counter of days remaining

1. Dashboard settings:
- Total amount needed
- Date end for the counter
- Field from the deals table to count in the counter

**Comment by despiegk** [comment]
we have the spreadsheet which is good enough for now

**Comment by Hamdy** [comment]
OK. closing this issue for now
