### ISSUE TITLE
Author last does not show up at Ambassador Deal Type

### ISSUE THREAD

**Issue by andhartl** [Incubaid/crm#144]
Can not see Author Last value on Ambassador Deal Type. PLs fix. Thank you

**Comment by andhartl** [comment]
same issue with other dealtypes. For details see here: https://crm.threefoldtoken.com/deal/?sort=7&desc=1****

**Comment by Hamdy** [comment]
After talking to @andhartl . this issue no longer exists so marking as won't fix and closing
