### ISSUE TITLE
uid

### ISSUE THREAD

**Issue by despiegk** [Incubaid/crm#18]
- check also hamdy's work
- he has the UID's nicely implemented

all in the url's 
http://127.0.0.1:8000/admin/company/company/b1ea/review/

will this be doable in flask?
we now just need to know that it is doable

**Comment by xmonader** [comment]
![selection_088](https://user-images.githubusercontent.com/64129/30063022-736399f8-924d-11e7-946b-c115b78c47f9.png)


It's doable from flask-admin and the urls are fixed automagically

**Comment by xmonader** [comment]
updates on branch useuuid

**Comment by despiegk** [comment]
can't we have clean url's like 127.0.0.1/user/4n23?view=detail
just example

**Comment by despiegk** [comment]
not urgent now !!!
