### ISSUE TITLE
graphql?

### ISSUE THREAD

**Issue by despiegk** [Incubaid/crm#19]
![image](https://user-images.githubusercontent.com/6021844/30145985-ac58409e-9395-11e7-9ee5-339604acd2a1.png)

```graphql
query contacts {
  sprints {
    comments {
      content
    }
  }
}

```

**Comment by xmonader** [comment]
Edit: apparently it was caused by a typo: all fixed
https://github.com/Incubaid/crm/commit/42090a2c8477cd4037143111c93d20e35f0c1fba
