### ISSUE TITLE
root objects & order

### ISSUE THREAD

**Issue by despiegk** [Incubaid/crm#2]
to show & in this order
- company
- contact
- deal
- project
- sprint
- task

not to show in top
- message
- tel/email
- comment
- link

**Comment by xmonader** [comment]
Fixed in https://github.com/Incubaid/crm/commit/01bea7ff80a9f5e2ab189c1f9276a455f45ff607
![screenshot_2017-09-03_11-28-49](https://user-images.githubusercontent.com/64129/30001893-6cf3561c-90a4-11e7-96b5-5c63ec14a27a.png)
