### ISSUE TITLE
deal/create new record/dealtype: remove PREPTO, add Ambassador

### ISSUE THREAD

**Issue by andhartl** [Incubaid/crm#25]
pls remove PREPTO and add Ambassador instead

**Comment by andhartl** [comment]
<img width="601" alt="screen shot 2017-09-11 at 09 01 33" src="https://user-images.githubusercontent.com/18591016/30263013-9f51c00a-96d3-11e7-91f9-d37d50434521.png">

**Comment by xmonader** [comment]
Fixed in master
