### ISSUE TITLE
do not show the nothing to show message (-:

### ISSUE THREAD

**Issue by despiegk** [Incubaid/crm#3]
![image](https://user-images.githubusercontent.com/6021844/30000590-91c802a8-9072-11e7-9110-60a603760ed8.png)

is there possibility to show nothing not even the field in the view page
just ignore the field when not used

do this for all objects

**Comment by xmonader** [comment]
Fixed in https://github.com/Incubaid/crm/commit/dacdfd68b979ee7be32674c4dcba7ab24825327c
