### ISSUE TITLE
support for IYO

### ISSUE THREAD

**Issue by despiegk** [Incubaid/crm#32]
- put caddy in front of CRM using IYO (https://github.com/itsyouonline/caddy-integration)
   - ask in scope tel nr & email addr & login
   - test this using our bash tools (jumpscale), install ZInstallerDocgenerator
- add author_org &  author_last field to each table (put in BASE class)
- change BASE class to get this info from the request (if it exists) & add to fields
   - if it does not exist do not fail & add this info to author_org & author_last
   - org is the 1e one , the original author, last is each modification
- when user logs in first time (need a way how to know this is first time)
   - check if user already exists in user table, if not add the info like username, tel & email to the user table (so we automatically populate this user table with info from IYO)

goal: this will tell us about who made changes

**Comment by xmonader** [comment]
implemented here keeping track of the creator and the last editor

https://github.com/Incubaid/crm/pull/84
