### ISSUE TITLE
markdown should not be shown in lists

### ISSUE THREAD

**Issue by despiegk** [Incubaid/crm#33]
![image](https://user-images.githubusercontent.com/6021844/30519107-53c3fcd8-9b8e-11e7-8c07-662283ce226b.png)

put a formatter which only shows first max 3 lines and text only
otherwise the grid's get too big

**Comment by xmonader** [comment]
https://github.com/Incubaid/crm/commit/5638763d3789f3ea46a9206dcfa8b3e14bb623c6
