### ISSUE TITLE
need instructions how to use postgresql as backend

### ISSUE THREAD

**Issue by despiegk** [Incubaid/crm#35]
- use bash tools & deploy container: ZInstallerDocgenerator
- use prefab to deploy postgresql inside
- create app: crm in prefab which installs & configures crm
   - call postgresql install
   - call caddy install (for optional IYO integration)
   - connects to postgresql

**Comment by despiegk** [comment]
let the following work:
https://github.com/Jumpscale/bash/commit/080913e50519ae5af8c7be3bad2db44f3bc2dfbc

**Comment by xmonader** [comment]
Prefab module https://github.com/Jumpscale/prefab9/commit/9d6e14c7883ab0f2cd02e63dccef5be58f958e38 and docs updated for how to have a postgres backend
