### ISSUE TITLE
state needs to be in task

### ISSUE THREAD

**Issue by despiegk** [Incubaid/crm#36]
![image](https://user-images.githubusercontent.com/6021844/30519163-45c8a204-9b8f-11e7-80b7-b13630551d03.png)

so we can change state of a task

**Comment by despiegk** [comment]
also assignee (who is responsible for this task)

![image](https://user-images.githubusercontent.com/6021844/30519170-5afbafe0-9b8f-11e7-87c7-2f1d3f7c7a91.png)

**Comment by despiegk** [comment]
for all clarity:
- tasks can be linked to most objects: contacts, companies, deals, projects, milestones and even more than 1 at same time.
- the assignee is the user who is responsible for that the task gets done

**Comment by xmonader** [comment]
![selection_097](https://user-images.githubusercontent.com/64129/30519728-ad3a7940-9b9d-11e7-99c2-273b360b87fe.png)

https://github.com/Incubaid/crm/commit/32d62939ae62dbdca407ba3796b450477565320f

**Comment by Hamdy** [comment]
@xmonader  Add (Assignee & state) to List view
Also in view Task, we need to rename (contact) to Assignee

**Comment by xmonader** [comment]
Implemented here https://github.com/Incubaid/crm/commit/6bf8ae71abfe0f579bfa2f769e749a188e83cd8e https://github.com/Incubaid/crm/commit/e4ce42f323c374e9b20c122eaa2205d7f56768e6
