### ISSUE TITLE
messages fixes & improvements

### ISSUE THREAD

**Issue by despiegk** [Incubaid/crm#37]
![image](https://user-images.githubusercontent.com/6021844/30519232-cfa6d440-9b90-11e7-87e6-58aef250998c.png)

lets make sure we can add messages to contact.
we need mod date attached to it & author.

**Comment by despiegk** [comment]
messages need to be available on
- project
- deal
- company
- contact
- user
- sprint

add already an author field to the message obj (today manual selection from users table)

make sure all views are ok

**Comment by xmonader** [comment]
So author is always a User?
mod_date isn't that the same as updated_at field?

**Comment by xmonader** [comment]
Fixes in https://github.com/Incubaid/crm/commit/f5f77580dde3e231662fb1910ac83f05a678a22f for the views

**Comment by despiegk** [comment]
mod_date = updated...

author indeed is always a user

**Comment by despiegk** [comment]
![image](https://user-images.githubusercontent.com/6021844/30523621-17c3b712-9be5-11e7-88a2-210ef28e57b9.png)

author not visible

**Comment by despiegk** [comment]
forgot to mention, message also on task

**Comment by xmonader** [comment]
![screenshot_2017-09-17_20-32-21](https://user-images.githubusercontent.com/64129/30523772-0542b0ce-9bf0-11e7-91e0-f2d80a67d654.png)
Author won't be shown if Empty

Messages added to task
