### ISSUE TITLE
sprint obj

### ISSUE THREAD

**Issue by despiegk** [Incubaid/crm#4]
- same remarks as #1 
- name & description first
- in edit page no need to show the linked tasks, idea is that sprint is chosen on the task linked to it e.g. task get's linked to a sprint, no need to do this here
-

**Comment by xmonader** [comment]
![screenshot_2017-09-03_15-26-13](https://user-images.githubusercontent.com/64129/30003379-a18ffd38-90c4-11e7-91c1-f43f4ec85b83.png)

All above are applied now, note: only the messages are allowed to be created in the edit page in sprint
