### ISSUE TITLE
edit comment crashes

### ISSUE THREAD

**Issue by despiegk** [Incubaid/crm#45]
![image](https://user-images.githubusercontent.com/6021844/30523616-e3d147b2-9be4-11e7-8e4a-31ffdc8e87d0.png)

also: can we support content as markdown field please

**Comment by xmonader** [comment]
https://github.com/Incubaid/crm/commit/aceffa1964b9b603beeaac5c50e95a312697c9fc

**Comment by Hamdy** [comment]
Verified and working
