### ISSUE TITLE
Company: Add Contact field

### ISSUE THREAD

**Issue by andhartl** [Incubaid/crm#65]
Pls add contact field to company so contacts can be associated with company

**Comment by xmonader** [comment]
![selection_099](https://user-images.githubusercontent.com/64129/30781312-32f4e992-a11d-11e7-9a19-7adc396ab70d.png)

![selection_100](https://user-images.githubusercontent.com/64129/30781311-32c2ac98-a11d-11e7-809c-89c7594577d6.png)

Can contact belong to many companies?
