### ISSUE TITLE
Contact: Add Subgroup dropdown field

### ISSUE THREAD

**Issue by andhartl** [Incubaid/crm#68]
We want mirror the ItsYou.Online subgroups on the contact level. pls add for this a dropdown field called Subgroup with the ability to select multiple subgroups.
The subgroups are:
Ambassadors
Investors
Hosters
Members
Public

**Comment by xmonader** [comment]
Subgroups are added and customizable than just the hardcoded groups, a CRM user can totally add/edit the subgroup and ad it to a contact.
