### ISSUE TITLE
easy way to add tasks

### ISSUE THREAD

**Issue by despiegk** [Incubaid/crm#7]
should be easy to add task to any of the related objects

from the object itself, now way too cumbersome

**Comment by xmonader** [comment]
I find it more suitable to use Tasks tab to create tasks. 
in the edit of objects related to tasks you can create tasks directly from there.

Do you prefer adding link in the "Home" page to create task page?

**Comment by despiegk** [comment]
inline is good to create new ones, but should only show latest e.g. 10 tasks inline and the rest should move to a tab

**Comment by xmonader** [comment]
I checked the django project, it displays all of them in a table "tabular inline views" not done using tabs and changes to that through a popup.
