### ISSUE TITLE
login procedure

### ISSUE THREAD

**Issue by despiegk** [Incubaid/crm#75]
- ONLY IYO users from group threefold.crm_users can login
- automatic creation of users record with name,emails,tels

**Comment by despiegk** [comment]
we need to check how a subgroup

![image](https://user-images.githubusercontent.com/6021844/30781882-a4ef7684-a127-11e7-9aa0-7b007cb6fca5.png)

can have access to graphql of CRM
and also we need to make sure we create a system user called: mailer_app (in this case)

**Comment by xmonader** [comment]
initial implementation to autoregister the user when first login to iyo
https://github.com/Incubaid/crm/commit/89be2b1579e10fae79e59086103829b9cdc12837
