### ISSUE TITLE
export/import to yaml or json files

### ISSUE THREAD

**Issue by despiegk** [Incubaid/crm#8]
/$objtype/$uid_$name.yaml

**Comment by despiegk** [comment]
this can be very generic usable export, we will for sure create more organized & structured later.
now something easy.
- I suggest put export method on base class
- create script which walks over all objects & calls export

**Comment by Hamdy** [comment]
export & import commands added to the set of commands the application support
exported data goes into a configurable directory in ```settings.DATA_DIR```
Please refer to README.md for how this works

**Comment by despiegk** [comment]
think messages & comments & some other things missing
can we export messages, comments, links always as inside the json of the object
e.g. inside the contact, so not as separate message obj

**Comment by xmonader** [comment]
@despiegk It's really great idea to embed them in the root object! I was discussing that earlier with @Hamdy

**Comment by Hamdy** [comment]
@despiegk ```python manage.py dumpdata``` now is aware of related models and embeds them automatically in dumped json file

**Comment by despiegk** [comment]
think we have double info now because e.g. messages are still as separate root object

**Comment by Hamdy** [comment]
@despiegk well, the thing is
Think of this scenario
Contact(A) has Task1 assigned
Contact(B) has Task1 assigned

If you want to change (Task1) you can't edit it in neither (contact(A) data nor Contact(B) data
You have to change it in Tasks objects themselves

the (Task1) data in both (contact A, B) data is also used for display only
we don't use it to reconstruct database record.
To construct database record we use actual tasks files 

Also the tasks, messages, etc in (Contact data) doesn't contain all info about a task
forexample (Task1) data in ContactA shouldn't have (all assignees) of that task, coz it's irrelevant to this contact and also will be very slow to retrieve that info, not to mention it will make a contact json very long

what do u think?
