### ISSUE TITLE
2 Users can be created with same info  

### ISSUE THREAD

**Issue by john-kheir** [Incubaid/crm#87]
Same issue for company, contact, .. etc
![bug1](https://user-images.githubusercontent.com/15011431/31052903-116215e2-a691-11e7-8a88-216cc10b20fc.png)

**Comment by xmonader** [comment]
Uniqueness is provided from iyo, and the system is always behind caddy to ensure that.

**Comment by john-kheir** [comment]
Even if the user uniqueness is insured by iyo .. what about company, contact, organizations pages, ... etc? .. These pages have the same issue

**Comment by Hamdy** [comment]
Now we have a (username) field which is unique and coming from IYO
so no 2 users are allowed to have same username.
username can be (empty)/(null) to support any data added to crm with no username, however we update userinfo on login from IYO so empty usernames shouldn't happen
