### ISSUE TITLE
Missing Info when pressing "Save and Continue Editing"

### ISSUE THREAD

**Issue by john-kheir** [Incubaid/crm#89]
## Scenario

1- Create user with certain company
![bug3-1](https://user-images.githubusercontent.com/15011431/31053041-796a659c-a694-11e7-886e-e1627ced9f6e.png)

2- Then press "Save and Continue Editing" 
![bug3-2](https://user-images.githubusercontent.com/15011431/31053096-d2b80630-a695-11e7-92be-56c7e8929d91.png)

## Actual Result
3- The user will be saved without the company info.  (also without organization, backupcompany, .. etc)
![bug3-3](https://user-images.githubusercontent.com/15011431/31053044-7c584f62-a694-11e7-82e9-995665c315a2.png)

## Expected Result 
All info in the first figure need to be there when pressing "Save and Continue Editing"

**Comment by xmonader** [comment]
Save and continue is all gone now
