### ISSUE TITLE
Not all of the provided relationships exist

### ISSUE THREAD

**Issue by john-kheir** [Incubaid/crm#91]
- Test messages, comments & links to user/contact/deal/project/sprint/company --> some of these relationships are not there
 - In detail view on comments we need to see author & moddate (so in relation to last change) --> please implement this as well

**Comment by john-kheir** [comment]
- Company page doesn't have link or do it from the link page 
- Deal Page doesn't have links or messages .. If Link and message pages have Deals and that's enough then it's okay

**Comment by Hamdy** [comment]
I think these are all solved now, 
Fixed edit link form on testing env to contain more fields as well
